User Management functionality
UnlockedLabs/UnlockEdv2 pull request #141
Opened 2024-03-18 02:02 UTC by Outragedpillow

Features:
Added functionality to the reset user password button. This gives the user a temporary password to use and will have them reset it at the next login
![uiPwResetInit](https://github.com/UnlockedLabs/UnlockEdv2/assets/123181203/44098147-0e9e-4c04-8875-b78aeecf3835)

Success: 
![uiResetPwSuccess](https://github.com/UnlockedLabs/UnlockEdv2/assets/123181203/9649f867-c78e-40e5-8a4f-da757a73ab0c)

If an account is an admin give an error:
![uiResetPwFail](https://github.com/UnlockedLabs/UnlockEdv2/assets/123181203/9fcca46d-964e-464c-8a63-72fbea2d863a)

Also added functionality to delete user button. For the moment allows deletion of both admin and student user types.
success: 
![uiDeleteSuccess](https://github.com/UnlockedLabs/UnlockEdv2/assets/123181203/d05d7cd0-730d-4336-91c0-202f09931b07)

These use a toast to display success or error that auto closes after a set time (5 seconds).
Rather than have a separate toast for different situations, made a dynamic toast that accepts a message, type, and has a bool for whether it should be displayed or not. 

Fixes:
#127 This was also fixed in my last PR and that code is implemented here as well
#124 modal now closes on submit. Response object was being misused.
#108 fixed issue. Enum validation was not working and had to be done manually for now. See Http/Controllers/v1/UserController.php

2024-03-18 20:48 UTC, calisio requested changes
Super small changes! @PThorpe92 will review StudentNewPasswordController and UserController.

2024-03-18 20:48 UTC, calisio commented on resources/js/Pages/Users.tsx
> +                            className="btn btn-warning"
For consistency sake (until we get a component that is used for all modals), could you modify these modals to follow the same format as left menu management modals? ie. color should be btn-error (or you can change the left menu modals to btn-warning... either way), close button should be left aligned, and all modals should have an "x" on the top right corner. Super small changes (and I know they existed before your PR) but keeps the UI consistent!

2024-03-18 20:48 UTC, calisio commented on resources/js/Components/forms/AddUserForm.tsx
> +                                    "Username shoudl be 50 characters or less",
small type on "should"

2024-03-18 20:48 UTC, calisio commented on resources/js/Pages/Users.tsx
> +                        <CheckCircleIcon className="h-6" />
When its an error, can you render `<ExclamationCircleIcon className="h-6" />` instead?

2024-03-18 22:38 UTC, PThorpe92 approved these changes
Other than what @calisio pointed out, looks good to me on the back-end. 

That UserRole enum issue has been driving me insane. I tried __everything__ and the only way to fix it was manually editing the user model like you did. :+1:

2024-03-19 13:32 UTC, Outragedpillow commented
Thanks for the feedback @calisio! I will make these changes today. And yeah @PThorpe92 I wasn't sure if that was the best fix but it works for now

2024-03-26 14:52 UTC, calisio approved these changes

2024-03-26 14:52 UTC, merged