UN-180 and UN-181 Category model and crud
UnlockedLabs/UnlockEdv2 pull request #31
Opened 2023-12-14 16:33 UTC by coledykstra

UN-180 Add Category model and migration
UN-181 Add basic Category crud controller

2023-12-14 17:17 UTC, PThorpe92 requested changes

2023-12-14 17:17 UTC, PThorpe92 commented on app/Http/Controllers/v1/CategoryController.php
> +        return response()->json($categories, Response::HTTP_OK);
We return API responses with Laravel's `Resource` type. You can do `php artisan make:resource CategoryResource`

You can look at Chris' latest PR for reference, but you are essentially defining the structure of exactly what you want to return. [here](https://github.com/chrissantillan/UnlockEdv2/blob/17bbac8fb3ecad79bbbab65ab0468443e3148aa7/app/Http/Resources/ProviderPlatformResource.php)

Then you can return things from your controllers by doing `CategoriesResource::collection($categories)`

Also you can do `Category::all()->paginate(10);`

2023-12-14 17:17 UTC, PThorpe92 commented on app/Http/Controllers/v1/CategoryController.php
> +            // Add other validation rules for your fields
// Add other validation rules for your fields ;)

2023-12-14 17:17 UTC, PThorpe92 commented on database/seeders/CategorySeeder.php
> +        //
This should run the seeder, you can look at others in the code base for reference

2023-12-14 17:17 UTC, PThorpe92 commented on app/Http/Controllers/v1/CategoryController.php
> +            // Add other validation rules for your fields
You can reference other Request types in the code base, so validation can be called on the requests with the
`$request->validated()` method. 
[reference](https://github.com/chrissantillan/UnlockEdv2/blob/17bbac8fb3ecad79bbbab65ab0468443e3148aa7/app/Http/Requests/StoreProviderPlatformRequest.php)

can also be generated with the `php artisan make:request CategoryRequest`

2023-12-14 19:25 UTC, coledykstra commented
I did the `git commit -m "fix: resolved api returns Category Resources and validator checks 3 field"` but i am lost what to do next.

2023-12-14 23:32 UTC, PThorpe92 approved these changes

2023-12-15 00:05 UTC, nokierae approved these changes

2023-12-15 00:05 UTC, merged