added responsive design to pills
UnlockedLabs/UnlockEdv2 pull request #359
Opened 2024-08-23 19:35 UTC by MillerSenior

[Screen Shot 2024-08-23 at 2.23.28 PM.pdf](https://github.com/user-attachments/files/16732979/Screen.Shot.2024-08-23.at.2.23.28.PM.pdf)
[Screen Shot 2024-08-23 at 2.24.03 PM.pdf](https://github.com/user-attachments/files/16732982/Screen.Shot.2024-08-23.at.2.24.03.PM.pdf)

2024-09-03 14:40 UTC, jtucholski commented
@MillerSenior Rather than making the pills take up the container width, can you keep their width limited to the text of the pill?

What if you tried getting rid of space-y-2? Or applied it for smaller screen sizes but blocked it from larger screen sizes? Like this (screenshot when it is properly applied and not at the same time, faked using Inspector).

![image](https://github.com/user-attachments/assets/deefb9dc-6846-4c3f-a1ad-74b7558abed3)

2024-09-03 14:48 UTC, jtucholski requested changes

2024-09-03 14:48 UTC, jtucholski commented on frontend/src/Components/CatalogCourseCard.tsx
Try seeing if you can use `space-y-2` for smaller screens and removing it for larger screens (whenever the pills stack). This might be the only change that's necessary. No need to change all the other pills to `inline-flex` or `items-center`.

2024-09-03 18:50 UTC, MillerSenior commented
Updated CatalogCourseCard.tsx, closes #359

2024-09-04 17:09 UTC, jtucholski approved these changes

2024-09-04 17:13 UTC, merged