feat: updated to use table-2
UnlockedLabs/UnlockEdv2 pull request #421
Opened 2024-10-10 03:27 UTC by MillerSenior

## Description of the change
UI updates on student and admin management pages to include table-2 functionality

![Screenshot 2024-10-09 222528](https://github.com/user-attachments/assets/215a4296-86aa-4ea9-b38e-5258f1aabd8b)
![Screenshot 2024-10-09 222539](https://github.com/user-attachments/assets/7ec3b060-1ecb-477f-bd13-d93fecd18ac6)
 
closes #395

2024-10-10 12:12 UTC, jtucholski commented
@MillerSenior Can we fix this so that the horizontal scroll bars aren't visible?

2024-10-10 16:54 UTC, calisio requested changes
Look so great!! Just a few residual changes and it should be good to go-- in addition to Josh's comment on the scrollbars!

2024-10-10 16:54 UTC, calisio commented on frontend/src/Pages/StudentManagement.tsx
> +                            <th>Last Active</th>
Keep this as "Last Updated".. "Last Active" is not an accurate label column because the user is not updated with data when they are active!

2024-10-10 16:54 UTC, calisio commented on frontend/src/Pages/StudentManagement.tsx
>  } from '@heroicons/react/20/solid';
make sure to change this to `@heroicons/react/24/outline` (or really just move those icons into the import on line 30)

2024-10-10 16:54 UTC, calisio commented on frontend/src/Pages/AdminManagement.tsx
>  } from '@heroicons/react/20/solid';
make sure to change this to `@heroicons/react/24/outline`

2024-10-14 19:12 UTC, calisio approved these changes

2024-10-14 19:12 UTC, merged