Remove dropdown
UnlockedLabs/UnlockEdv2 pull request #503
Opened 2024-11-14 00:14 UTC by MillerSenior

Here's a paragraph and checklist that you can use to describe the changes made to the application to conform with the assignment:

### Paragraph
I have updated the application to streamline the user role assignment process based on the context from which the form is accessed. The dropdown component for selecting roles has been removed from the add student, edit student, and add admin pages. Now, the role is automatically assigned depending on whether the user accesses the form from the Admin Management or Student Management screens. This update ensures that the role field is hidden and contextually relevant roles are assigned automatically. Additionally, new components have been implemented to handle the editing of student roles specifically. Changes were made to `user.tsx` to conditionally handle role values, depending on the screen from which the user is adding or editing a user. Furthermore, backend modifications are required to save usernames containing numbers, such as "Iamnumber1," for both add and edit forms.

### Checklist
- **Removed Dropdown Component**:
  - Removed from add student page
  - Removed from edit student page
  - Removed from add admin page
- **Automatic Role Assignment**:
  - Role automatically assigned based on the screen (Admin Management or Student Management)
  - Role field hidden in the form
- **Component Implementation**:
  - Implemented components to handle edit student functionality
- **User.tsx Modifications**:
  - Added functionality to conditionally handle role values based on the screen
- **Backend Changes Needed**:
  - Ensure saving usernames containing numbers (e.g., "Iamnumber1") is supported in both add and edit forms

These updates enhance the user experience by making role assignments seamless and intuitive based on the user's context while maintaining compatibility with the backend system. Closes #443

2024-11-18 16:35 UTC, jtucholski requested changes
@MillerSenior I've looked at this and given a few comments. Can you work through them and push again?

2024-11-18 16:35 UTC, jtucholski commented on frontend/src/Pages/AdminManagement.tsx
> -                                'Account Created ↓ ': 'created_at desc',
I don't think this PR should've changed these icons. The v and the ^ character don't fit as well as the arrows. I'd recommend restoring it to the arrows and doing the same for `StudentManagement` as well.

![image](https://github.com/user-attachments/assets/41a10bc5-de0a-453c-bff8-5ae34da125bf)

2024-11-18 16:35 UTC, jtucholski commented on frontend/src/Pages/AdminManagement.tsx
> +                item="Administrator"
Stick with Admin (over Administrator) since all other parts of the page such as the titles and buttons use **Admin**

2024-11-18 16:35 UTC, jtucholski commented on frontend/src/Pages/AdminManagement.tsx
> +                item="Administrator"
This should stay as Admin.

2024-11-18 16:35 UTC, jtucholski commented on frontend/src/Pages/AdminManagement.tsx
> +                item="Delete Administrator"
Stick with Admin

2024-11-18 16:35 UTC, jtucholski commented on frontend/src/Pages/StudentManagement.tsx
> +                                'Account Created v ': 'created_at desc',
See my other comment about AdminManagement. We should be using the icons and not `v` or `^`

2024-11-18 16:38 UTC, jtucholski commented on frontend/src/Pages/Users.tsx
How did you test this? I don't think this page is used anywhere in the application.

2024-11-18 16:47 UTC, jtucholski commented on frontend/src/Pages/Users.tsx
Upon further review, Users.tsx was a file that was kept around and shouldn't exist. Can you delete it with this PR as a cleanup?

2024-11-20 18:17 UTC, MillerSenior commented
All changes have been made to specifications of @jtucholski.

2024-11-21 21:08 UTC, closed without merging