Replace Open Content with Knowledge Center
UnlockedLabs/UnlockEdv2 pull request #533
Opened 2024-11-26 00:50 UTC by corypride

## Description of the change

Renamed the Open Content page to Knowledge Center, updating the following areas:

Side Navigation:
For Admins, display the link as "Knowledge Center Management".
For Residents, display the link as "Knowledge Center".
Breadcrumb Page Title:
Update the page title in the breadcrumb to reflect the new names:
Admins: "Knowledge Center Management"
Residents: "Knowledge Center"
If possible consider refactoring any file names or types to reflect this change to knowledge center. * We may have an issue with the backend models and database tables and need to discuss if it's worth refactoring that at this point.

- **Related issues**: 
- Closes: #521 

## Screenshot(s)

https://github.com/user-attachments/assets/322da206-61b7-4cb0-b4bd-605f509a3a09

2024-11-26 16:04 UTC, calisio requested changes
Besides that one super small comment everything else looks good 👍

2024-11-26 19:32 UTC, corypride commented on frontend/src/Components/Navbar.tsx
> +                                                Knowledge Center Management
![image](https://github.com/user-attachments/assets/ce492349-f38a-47a0-9d26-a0ad3962e1f1)

2024-11-27 00:22 UTC, PThorpe92 commented
sorry bud this one is prob gonna have to be edited to match with the changes from @calisio's last PR that was just merged

2024-12-03 23:15 UTC, PThorpe92 approved these changes

2024-12-03 23:16 UTC, merged